In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Sanjeev Kallepalli\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Sanjeev Kallepalli\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Sanjeev Kallepalli\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Sanjeev Kallepalli\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Sanjeev Kallepalli\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Create a sample DataFrame

data = {
    'Name': ['Sansa', 'Jon', 'Cersei', 'Ned Stark'],
    'Age': [25, 30, 35, 40],
    'City': ['Winterfell', 'Dragonstone', 'King\'s Landing', 'Winterfell']
}

print(type(data))
df = pd.DataFrame(data)

<class 'dict'>

In [3]:
df

        Name  Age            City
0      Sansa   25      Winterfell
1        Jon   30     Dragonstone
2     Cersei   35  King's Landing
3  Ned Stark   40      Winterfell

In [4]:
df.head() # Display the first 5 rows of the DataFrame

        Name  Age            City
0      Sansa   25      Winterfell
1        Jon   30     Dragonstone
2     Cersei   35  King's Landing
3  Ned Stark   40      Winterfell

In [5]:
df.head(1) # Display the first row of the DataFrame

    Name  Age        City
0  Sansa   25  Winterfell

In [6]:
df.tail(1)

        Name  Age        City
3  Ned Stark   40  Winterfell

In [7]:
# selecting a column
df['Name']

0        Sansa
1          Jon
2       Cersei
3    Ned Stark
Name: Name, dtype: str

In [9]:
df[['Name']]

        Name
0      Sansa
1        Jon
2     Cersei
3  Ned Stark

In [8]:
# selecting 2 columns
df[['Name', 'City']] # use double brackets to select multiple columns

        Name            City
0      Sansa      Winterfell
1        Jon     Dragonstone
2     Cersei  King's Landing
3  Ned Stark      Winterfell

In [10]:
df[df['Age'] > 30]

        Name  Age            City
2     Cersei   35  King's Landing
3  Ned Stark   40      Winterfell

In [11]:
# filtering rows based on a condition
df[df['Age'] > 30] # Select rows where Age is greater than 30

        Name  Age            City
2     Cersei   35  King's Landing
3  Ned Stark   40      Winterfell

In [ ]:
# Get only selected columns with a condition
df[df['Age'] > 30][['Name', 'City']] # Select Name and City for rows where Age is greater than 30

        Name            City
2     Cersei  King's Landing
3  Ned Stark      Winterfell

In [ ]:
# iloc and loc

In [13]:
df2 = df[df['Age'] > 30][['Name', 'City']]

In [14]:
df2

        Name            City
2     Cersei  King's Landing
3  Ned Stark      Winterfell

In [15]:
df2.iloc[0]

Name            Cersei
City    King's Landing
Name: 2, dtype: str

In [16]:
df2.loc[2, :]

Name            Cersei
City    King's Landing
Name: 2, dtype: str

In [17]:
df2.loc[0, :]

KeyError: 0