In [1]:
import pandas as pd

df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [2]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [4]:
# common operations with pandas
df['Attrition'].value_counts() # count the number of occurrences of each value in the 'Attrition' column

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [5]:
df.dtypes # check the data types of each column

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [6]:
# update Attrition column to be 1 for Yes and 0 for No
df['Attrition_1'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [7]:
df[['Attrition', 'Attrition_1']].head()

  Attrition  Attrition_1
0       Yes            1
1        No            0
2       Yes            1
3        No            0
4        No            0

In [8]:
# or you can use apply with a lambda function
df['Attrition_2'] = df['Attrition'].apply(lambda x: 1 if x == 'Yes' else 0)

In [9]:
df[['Attrition', 'Attrition_1', 'Attrition_2']].head()

  Attrition  Attrition_1  Attrition_2
0       Yes            1            1
1        No            0            0
2       Yes            1            1
3        No            0            0
4        No            0            0

In [10]:
# or you can use np.where
import numpy as np
df['Attrition_3'] = np.where(df['Attrition'] == 'Yes', 1, 0)

In [11]:
# or you can also use .loc
df.loc[df['Attrition'] == 'Yes', 'Attrition_4'] = 1
df.loc[df['Attrition'] == 'No', 'Attrition_4'] = 0

In [12]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition_1', 'Attrition_2', 'Attrition_3',
       'Attrition_4'],
      dtype='str')

In [13]:
cols = [col for col in df.columns if 'Attrition' in col]
df[cols].head()

  Attrition  Attrition_1  Attrition_2  Attrition_3  Attrition_4
0       Yes            1            1            1          1.0
1        No            0            0            0          0.0
2       Yes            1            1            1          1.0
3        No            0            0            0          0.0
4        No            0            0            0          0.0

In [14]:
# get rid of all columns we created.
cols_to_drop = [col for col in df.columns if 'Attrition_' in col]
# .drop drops the columns.
# inplace=True means we want to modify the original dataframe
#  instead of creating a new one.
df.drop(columns=cols_to_drop, inplace=True)

In [15]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [16]:
# if column does not exist, it will raise an error.
df.drop(columns=['Attrition_1'], inplace=True)

KeyError: "['Attrition_1'] not found in axis"

In [17]:
try:
    a = 1 + 1
except Exception as e:
    print(f"An error occurred: {e}")

In [18]:
a

2

In [19]:
# error capture
# only KeyError will be captured, if there is another error, it will not be captured.
try:
    df.drop(columns=['Attrition_1'], inplace=True)
except KeyError as e:
    print(f"Error: {e}")

Error: "['Attrition_1'] not found in axis"

In [20]:
try:
    a = 1 / 0
except KeyError as e:
    print(f"KeyError: {e}")

ZeroDivisionError: division by zero

In [21]:
try:
    a = 1 / 0
except ZeroDivisionError as e:
    print(f"Zero Division Error: {e}")

Zero Division Error: division by zero

In [22]:
# generic exception handling
try:
    a = 1/0
except Exception as e:
    print(f'Exception occured due to {e}')

Exception occured due to division by zero

In [25]:
df['Attrition'].dtype

In [27]:
# modify Attrition
df.loc[df['Attrition'] == 'Yes', 'Attrition'] = '1'
df.loc[df['Attrition'] == 'No', 'Attrition'] = '0'

df['Attrition'] = df['Attrition'].astype(int)

In [28]:
# check the distribution of Attrition
df.groupby('Attrition').size()

Attrition
0    1233
1     237
dtype: int64

In [29]:
# which Department has the highest attrition rate?
df.groupby('Department').agg({'Attrition': 'sum'}).sort_values(by='Attrition', ascending=False)

                        Attrition
Department
Research & Development        133
Sales                          92
Human Resources                12

In [32]:
# validate this
df[df['Department']=='Human Resources']['Attrition'].value_counts()

Attrition
0    51
1    12
Name: count, dtype: int64

In [31]:
df[df['Department'] == 'Human Resources']['Department'].value_counts()

Department
Human Resources    63
Name: count, dtype: int64